-- 2026-09 追加テンプレート 第2弾(8種)を preset_objects に登録する。
--
-- 福袋 / 桜 / 豆まき / お年玉 / クレーンゲーム / もぐらたたき / ボウリング / 巻物
-- 1テンプレートにつき6段階(1等〜6等)と4段階(大当たり/当たり/はずれ/クーポン)の両方を用意。
-- 焦らし用(<カテゴリ>_suspense_3d.glb)はファイル名から自動解決するため登録不要。
--
-- 同じ名前で二重登録されないよう、既存を消してから入れ直す。

delete from preset_objects where service = 'fukubiku' and category in ('fukubukuro','sakura','mamemaki','otoshidama','crane','mogura','bowling','makimono');

insert into preset_objects (name, category, model_url, service) values
  ('福袋 - 1等（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_1tou_3d.glb', 'fukubiku'),
  ('福袋 - 2等（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_2tou_3d.glb', 'fukubiku'),
  ('福袋 - 3等（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_3tou_3d.glb', 'fukubiku'),
  ('福袋 - 4等（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_4tou_3d.glb', 'fukubiku'),
  ('福袋 - 5等（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_5tou_3d.glb', 'fukubiku'),
  ('福袋 - 6等（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_6tou_3d.glb', 'fukubiku'),
  ('福袋 - 大当たり（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_ohatari_3d.glb', 'fukubiku'),
  ('福袋 - 当たり（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_atari_3d.glb', 'fukubiku'),
  ('福袋 - はずれ（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_hazure_3d.glb', 'fukubiku'),
  ('福袋 - クーポン（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_coupon_3d.glb', 'fukubiku'),
  ('福袋 - またね（3Dオブジェクト）', 'fukubukuro', '/presets/fukubukuro/fukubukuro_cookie_3d.glb', 'fukubiku'),
  ('桜 - 1等（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_1tou_3d.glb', 'fukubiku'),
  ('桜 - 2等（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_2tou_3d.glb', 'fukubiku'),
  ('桜 - 3等（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_3tou_3d.glb', 'fukubiku'),
  ('桜 - 4等（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_4tou_3d.glb', 'fukubiku'),
  ('桜 - 5等（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_5tou_3d.glb', 'fukubiku'),
  ('桜 - 6等（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_6tou_3d.glb', 'fukubiku'),
  ('桜 - 大当たり（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_ohatari_3d.glb', 'fukubiku'),
  ('桜 - 当たり（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_atari_3d.glb', 'fukubiku'),
  ('桜 - はずれ（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_hazure_3d.glb', 'fukubiku'),
  ('桜 - クーポン（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_coupon_3d.glb', 'fukubiku'),
  ('桜 - またね（3Dオブジェクト）', 'sakura', '/presets/sakura/sakura_cookie_3d.glb', 'fukubiku'),
  ('豆まき - 1等（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_1tou_3d.glb', 'fukubiku'),
  ('豆まき - 2等（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_2tou_3d.glb', 'fukubiku'),
  ('豆まき - 3等（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_3tou_3d.glb', 'fukubiku'),
  ('豆まき - 4等（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_4tou_3d.glb', 'fukubiku'),
  ('豆まき - 5等（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_5tou_3d.glb', 'fukubiku'),
  ('豆まき - 6等（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_6tou_3d.glb', 'fukubiku'),
  ('豆まき - 大当たり（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_ohatari_3d.glb', 'fukubiku'),
  ('豆まき - 当たり（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_atari_3d.glb', 'fukubiku'),
  ('豆まき - はずれ（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_hazure_3d.glb', 'fukubiku'),
  ('豆まき - クーポン（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_coupon_3d.glb', 'fukubiku'),
  ('豆まき - またね（3Dオブジェクト）', 'mamemaki', '/presets/mamemaki/mamemaki_cookie_3d.glb', 'fukubiku'),
  ('お年玉 - 1等（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_1tou_3d.glb', 'fukubiku'),
  ('お年玉 - 2等（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_2tou_3d.glb', 'fukubiku'),
  ('お年玉 - 3等（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_3tou_3d.glb', 'fukubiku'),
  ('お年玉 - 4等（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_4tou_3d.glb', 'fukubiku'),
  ('お年玉 - 5等（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_5tou_3d.glb', 'fukubiku'),
  ('お年玉 - 6等（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_6tou_3d.glb', 'fukubiku'),
  ('お年玉 - 大当たり（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_ohatari_3d.glb', 'fukubiku'),
  ('お年玉 - 当たり（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_atari_3d.glb', 'fukubiku'),
  ('お年玉 - はずれ（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_hazure_3d.glb', 'fukubiku'),
  ('お年玉 - クーポン（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_coupon_3d.glb', 'fukubiku'),
  ('お年玉 - またね（3Dオブジェクト）', 'otoshidama', '/presets/otoshidama/otoshidama_cookie_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 1等（3Dオブジェクト）', 'crane', '/presets/crane/crane_1tou_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 2等（3Dオブジェクト）', 'crane', '/presets/crane/crane_2tou_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 3等（3Dオブジェクト）', 'crane', '/presets/crane/crane_3tou_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 4等（3Dオブジェクト）', 'crane', '/presets/crane/crane_4tou_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 5等（3Dオブジェクト）', 'crane', '/presets/crane/crane_5tou_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 6等（3Dオブジェクト）', 'crane', '/presets/crane/crane_6tou_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 大当たり（3Dオブジェクト）', 'crane', '/presets/crane/crane_ohatari_3d.glb', 'fukubiku'),
  ('クレーンゲーム - 当たり（3Dオブジェクト）', 'crane', '/presets/crane/crane_atari_3d.glb', 'fukubiku'),
  ('クレーンゲーム - はずれ（3Dオブジェクト）', 'crane', '/presets/crane/crane_hazure_3d.glb', 'fukubiku'),
  ('クレーンゲーム - クーポン（3Dオブジェクト）', 'crane', '/presets/crane/crane_coupon_3d.glb', 'fukubiku'),
  ('クレーンゲーム - またね（3Dオブジェクト）', 'crane', '/presets/crane/crane_cookie_3d.glb', 'fukubiku'),
  ('もぐらたたき - 1等（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_1tou_3d.glb', 'fukubiku'),
  ('もぐらたたき - 2等（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_2tou_3d.glb', 'fukubiku'),
  ('もぐらたたき - 3等（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_3tou_3d.glb', 'fukubiku'),
  ('もぐらたたき - 4等（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_4tou_3d.glb', 'fukubiku'),
  ('もぐらたたき - 5等（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_5tou_3d.glb', 'fukubiku'),
  ('もぐらたたき - 6等（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_6tou_3d.glb', 'fukubiku'),
  ('もぐらたたき - 大当たり（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_ohatari_3d.glb', 'fukubiku'),
  ('もぐらたたき - 当たり（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_atari_3d.glb', 'fukubiku'),
  ('もぐらたたき - はずれ（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_hazure_3d.glb', 'fukubiku'),
  ('もぐらたたき - クーポン（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_coupon_3d.glb', 'fukubiku'),
  ('もぐらたたき - またね（3Dオブジェクト）', 'mogura', '/presets/mogura/mogura_cookie_3d.glb', 'fukubiku'),
  ('ボウリング - 1等（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_1tou_3d.glb', 'fukubiku'),
  ('ボウリング - 2等（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_2tou_3d.glb', 'fukubiku'),
  ('ボウリング - 3等（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_3tou_3d.glb', 'fukubiku'),
  ('ボウリング - 4等（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_4tou_3d.glb', 'fukubiku'),
  ('ボウリング - 5等（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_5tou_3d.glb', 'fukubiku'),
  ('ボウリング - 6等（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_6tou_3d.glb', 'fukubiku'),
  ('ボウリング - 大当たり（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_ohatari_3d.glb', 'fukubiku'),
  ('ボウリング - 当たり（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_atari_3d.glb', 'fukubiku'),
  ('ボウリング - はずれ（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_hazure_3d.glb', 'fukubiku'),
  ('ボウリング - クーポン（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_coupon_3d.glb', 'fukubiku'),
  ('ボウリング - またね（3Dオブジェクト）', 'bowling', '/presets/bowling/bowling_cookie_3d.glb', 'fukubiku'),
  ('巻物 - 1等（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_1tou_3d.glb', 'fukubiku'),
  ('巻物 - 2等（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_2tou_3d.glb', 'fukubiku'),
  ('巻物 - 3等（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_3tou_3d.glb', 'fukubiku'),
  ('巻物 - 4等（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_4tou_3d.glb', 'fukubiku'),
  ('巻物 - 5等（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_5tou_3d.glb', 'fukubiku'),
  ('巻物 - 6等（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_6tou_3d.glb', 'fukubiku'),
  ('巻物 - 大当たり（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_ohatari_3d.glb', 'fukubiku'),
  ('巻物 - 当たり（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_atari_3d.glb', 'fukubiku'),
  ('巻物 - はずれ（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_hazure_3d.glb', 'fukubiku'),
  ('巻物 - クーポン（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_coupon_3d.glb', 'fukubiku'),
  ('巻物 - またね（3Dオブジェクト）', 'makimono', '/presets/makimono/makimono_cookie_3d.glb', 'fukubiku');
