insert into preset_objects (name, category, model_url, thumbnail_url, service) values
  ('戦闘機の的撃ち - 当たり（3Dオブジェクト）', 'jet', 'https://app.fukubikiu.com/presets/jet/jet_atari_3d.glb', 'https://app.fukubikiu.com/presets/jet/jet_atari_3d_thumb.png', 'fukubiku'),
  ('戦闘機の的撃ち - 大当たり（3Dオブジェクト）', 'jet', 'https://app.fukubikiu.com/presets/jet/jet_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/jet/jet_ohatari_3d_thumb.png', 'fukubiku'),
  ('戦闘機の的撃ち - クーポン（3Dオブジェクト）', 'jet', 'https://app.fukubikiu.com/presets/jet/jet_coupon_3d.glb', 'https://app.fukubikiu.com/presets/jet/jet_coupon_3d_thumb.png', 'fukubiku'),
  ('戦闘機の的撃ち - はずれ（3Dオブジェクト）', 'jet', 'https://app.fukubikiu.com/presets/jet/jet_hazure_3d.glb', 'https://app.fukubikiu.com/presets/jet/jet_hazure_3d_thumb.png', 'fukubiku'),
  ('戦闘機の的撃ち - 参加賞（3Dオブジェクト）', 'jet', 'https://app.fukubikiu.com/presets/jet/jet_cookie_3d.glb', 'https://app.fukubikiu.com/presets/jet/jet_cookie_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 1等（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_1tou_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_1tou_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 2等（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_2tou_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_2tou_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 3等（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_3tou_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_3tou_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 4等（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_4tou_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_4tou_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 5等（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_5tou_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_5tou_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 6等（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_6tou_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_6tou_3d_thumb.png', 'fukubiku'),
  ('ロケット発射 - 参加賞（3Dオブジェクト）', 'rocket', 'https://app.fukubikiu.com/presets/rocket/rocket_cookie_3d.glb', 'https://app.fukubikiu.com/presets/rocket/rocket_cookie_3d_thumb.png', 'fukubiku'),
  ('隕石落下 - 当たり（3Dオブジェクト）', 'meteor', 'https://app.fukubikiu.com/presets/meteor/meteor_atari_3d.glb', 'https://app.fukubikiu.com/presets/meteor/meteor_atari_3d_thumb.png', 'fukubiku'),
  ('隕石落下 - 大当たり（3Dオブジェクト）', 'meteor', 'https://app.fukubikiu.com/presets/meteor/meteor_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/meteor/meteor_ohatari_3d_thumb.png', 'fukubiku'),
  ('隕石落下 - クーポン（3Dオブジェクト）', 'meteor', 'https://app.fukubikiu.com/presets/meteor/meteor_coupon_3d.glb', 'https://app.fukubikiu.com/presets/meteor/meteor_coupon_3d_thumb.png', 'fukubiku'),
  ('隕石落下 - はずれ（3Dオブジェクト）', 'meteor', 'https://app.fukubikiu.com/presets/meteor/meteor_hazure_3d.glb', 'https://app.fukubikiu.com/presets/meteor/meteor_hazure_3d_thumb.png', 'fukubiku'),
  ('隕石落下 - 参加賞（3Dオブジェクト）', 'meteor', 'https://app.fukubikiu.com/presets/meteor/meteor_cookie_3d.glb', 'https://app.fukubikiu.com/presets/meteor/meteor_cookie_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 1等（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_1tou_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_1tou_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 2等（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_2tou_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_2tou_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 3等（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_3tou_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_3tou_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 4等（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_4tou_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_4tou_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 5等（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_5tou_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_5tou_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 6等（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_6tou_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_6tou_3d_thumb.png', 'fukubiku'),
  ('手裏剣ヒット - 参加賞（3Dオブジェクト）', 'shuriken', 'https://app.fukubikiu.com/presets/shuriken/shuriken_cookie_3d.glb', 'https://app.fukubikiu.com/presets/shuriken/shuriken_cookie_3d_thumb.png', 'fukubiku'),
  ('龍が玉を掴む - 当たり（3Dオブジェクト）', 'dragon', 'https://app.fukubikiu.com/presets/dragon/dragon_atari_3d.glb', 'https://app.fukubikiu.com/presets/dragon/dragon_atari_3d_thumb.png', 'fukubiku'),
  ('龍が玉を掴む - 大当たり（3Dオブジェクト）', 'dragon', 'https://app.fukubikiu.com/presets/dragon/dragon_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/dragon/dragon_ohatari_3d_thumb.png', 'fukubiku'),
  ('龍が玉を掴む - クーポン（3Dオブジェクト）', 'dragon', 'https://app.fukubikiu.com/presets/dragon/dragon_coupon_3d.glb', 'https://app.fukubikiu.com/presets/dragon/dragon_coupon_3d_thumb.png', 'fukubiku'),
  ('龍が玉を掴む - はずれ（3Dオブジェクト）', 'dragon', 'https://app.fukubikiu.com/presets/dragon/dragon_hazure_3d.glb', 'https://app.fukubikiu.com/presets/dragon/dragon_hazure_3d_thumb.png', 'fukubiku'),
  ('龍が玉を掴む - 参加賞（3Dオブジェクト）', 'dragon', 'https://app.fukubikiu.com/presets/dragon/dragon_cookie_3d.glb', 'https://app.fukubikiu.com/presets/dragon/dragon_cookie_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 1等（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_1tou_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_1tou_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 2等（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_2tou_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_2tou_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 3等（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_3tou_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_3tou_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 4等（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_4tou_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_4tou_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 5等（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_5tou_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_5tou_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 6等（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_6tou_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_6tou_3d_thumb.png', 'fukubiku'),
  ('居合斬り - 参加賞（3Dオブジェクト）', 'iaido', 'https://app.fukubikiu.com/presets/iaido/iaido_cookie_3d.glb', 'https://app.fukubikiu.com/presets/iaido/iaido_cookie_3d_thumb.png', 'fukubiku'),
  ('UFOビーム - 当たり（3Dオブジェクト）', 'ufo', 'https://app.fukubikiu.com/presets/ufo/ufo_atari_3d.glb', 'https://app.fukubikiu.com/presets/ufo/ufo_atari_3d_thumb.png', 'fukubiku'),
  ('UFOビーム - 大当たり（3Dオブジェクト）', 'ufo', 'https://app.fukubikiu.com/presets/ufo/ufo_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/ufo/ufo_ohatari_3d_thumb.png', 'fukubiku'),
  ('UFOビーム - クーポン（3Dオブジェクト）', 'ufo', 'https://app.fukubikiu.com/presets/ufo/ufo_coupon_3d.glb', 'https://app.fukubikiu.com/presets/ufo/ufo_coupon_3d_thumb.png', 'fukubiku'),
  ('UFOビーム - はずれ（3Dオブジェクト）', 'ufo', 'https://app.fukubikiu.com/presets/ufo/ufo_hazure_3d.glb', 'https://app.fukubikiu.com/presets/ufo/ufo_hazure_3d_thumb.png', 'fukubiku'),
  ('UFOビーム - 参加賞（3Dオブジェクト）', 'ufo', 'https://app.fukubikiu.com/presets/ufo/ufo_cookie_3d.glb', 'https://app.fukubikiu.com/presets/ufo/ufo_cookie_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 1等（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_1tou_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_1tou_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 2等（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_2tou_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_2tou_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 3等（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_3tou_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_3tou_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 4等（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_4tou_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_4tou_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 5等（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_5tou_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_5tou_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 6等（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_6tou_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_6tou_3d_thumb.png', 'fukubiku'),
  ('大砲・クラッカー砲 - 参加賞（3Dオブジェクト）', 'cannon', 'https://app.fukubikiu.com/presets/cannon/cannon_cookie_3d.glb', 'https://app.fukubikiu.com/presets/cannon/cannon_cookie_3d_thumb.png', 'fukubiku'),
  ('雷神の一撃 - 当たり（3Dオブジェクト）', 'thunder', 'https://app.fukubikiu.com/presets/thunder/thunder_atari_3d.glb', 'https://app.fukubikiu.com/presets/thunder/thunder_atari_3d_thumb.png', 'fukubiku'),
  ('雷神の一撃 - 大当たり（3Dオブジェクト）', 'thunder', 'https://app.fukubikiu.com/presets/thunder/thunder_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/thunder/thunder_ohatari_3d_thumb.png', 'fukubiku'),
  ('雷神の一撃 - クーポン（3Dオブジェクト）', 'thunder', 'https://app.fukubikiu.com/presets/thunder/thunder_coupon_3d.glb', 'https://app.fukubikiu.com/presets/thunder/thunder_coupon_3d_thumb.png', 'fukubiku'),
  ('雷神の一撃 - はずれ（3Dオブジェクト）', 'thunder', 'https://app.fukubikiu.com/presets/thunder/thunder_hazure_3d.glb', 'https://app.fukubikiu.com/presets/thunder/thunder_hazure_3d_thumb.png', 'fukubiku'),
  ('雷神の一撃 - 参加賞（3Dオブジェクト）', 'thunder', 'https://app.fukubikiu.com/presets/thunder/thunder_cookie_3d.glb', 'https://app.fukubikiu.com/presets/thunder/thunder_cookie_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 1等（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_1tou_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_1tou_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 2等（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_2tou_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_2tou_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 3等（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_3tou_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_3tou_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 4等（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_4tou_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_4tou_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 5等（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_5tou_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_5tou_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 6等（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_6tou_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_6tou_3d_thumb.png', 'fukubiku'),
  ('超パンチ - 参加賞（3Dオブジェクト）', 'punch', 'https://app.fukubikiu.com/presets/punch/punch_cookie_3d.glb', 'https://app.fukubikiu.com/presets/punch/punch_cookie_3d_thumb.png', 'fukubiku')
on conflict (model_url) do update set
  name = excluded.name,
  category = excluded.category,
  thumbnail_url = excluded.thumbnail_url,
  service = excluded.service;
