-- 2026-09 追加テンプレート(8種)を preset_objects に登録する。
--
-- 1テンプレートにつき、6段階(1等〜6等)と4段階(大当たり/当たり/はずれ/クーポン)の
-- 両方を用意しているので、案件に応じてどちらでも選べる。
-- 「またね」はCookie保持中(クールダウン中)に表示されるもの。
-- 焦らし用(<カテゴリ>_suspense_3d.glb)はファイル名から自動で解決するため登録不要。
--
-- 同じ名前で二重登録されないよう、既存を消してから入れ直す。

delete from preset_objects where service = 'fukubiku' and category in
  ('sankaku','ema','kagamibiraki','xmas','vending','receipt','ring','safe');

insert into preset_objects (name, category, model_url, service) values
  ('三角くじ - 1等（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_1tou_3d.glb', 'fukubiku'),
  ('三角くじ - 2等（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_2tou_3d.glb', 'fukubiku'),
  ('三角くじ - 3等（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_3tou_3d.glb', 'fukubiku'),
  ('三角くじ - 4等（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_4tou_3d.glb', 'fukubiku'),
  ('三角くじ - 5等（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_5tou_3d.glb', 'fukubiku'),
  ('三角くじ - 6等（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_6tou_3d.glb', 'fukubiku'),
  ('三角くじ - 大当たり（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_ohatari_3d.glb', 'fukubiku'),
  ('三角くじ - 当たり（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_atari_3d.glb', 'fukubiku'),
  ('三角くじ - はずれ（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_hazure_3d.glb', 'fukubiku'),
  ('三角くじ - クーポン（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_coupon_3d.glb', 'fukubiku'),
  ('三角くじ - またね（3Dオブジェクト）', 'sankaku', '/presets/sankaku/sankaku_cookie_3d.glb', 'fukubiku'),
  ('絵馬 - 1等（3Dオブジェクト）', 'ema', '/presets/ema/ema_1tou_3d.glb', 'fukubiku'),
  ('絵馬 - 2等（3Dオブジェクト）', 'ema', '/presets/ema/ema_2tou_3d.glb', 'fukubiku'),
  ('絵馬 - 3等（3Dオブジェクト）', 'ema', '/presets/ema/ema_3tou_3d.glb', 'fukubiku'),
  ('絵馬 - 4等（3Dオブジェクト）', 'ema', '/presets/ema/ema_4tou_3d.glb', 'fukubiku'),
  ('絵馬 - 5等（3Dオブジェクト）', 'ema', '/presets/ema/ema_5tou_3d.glb', 'fukubiku'),
  ('絵馬 - 6等（3Dオブジェクト）', 'ema', '/presets/ema/ema_6tou_3d.glb', 'fukubiku'),
  ('絵馬 - 大当たり（3Dオブジェクト）', 'ema', '/presets/ema/ema_ohatari_3d.glb', 'fukubiku'),
  ('絵馬 - 当たり（3Dオブジェクト）', 'ema', '/presets/ema/ema_atari_3d.glb', 'fukubiku'),
  ('絵馬 - はずれ（3Dオブジェクト）', 'ema', '/presets/ema/ema_hazure_3d.glb', 'fukubiku'),
  ('絵馬 - クーポン（3Dオブジェクト）', 'ema', '/presets/ema/ema_coupon_3d.glb', 'fukubiku'),
  ('絵馬 - またね（3Dオブジェクト）', 'ema', '/presets/ema/ema_cookie_3d.glb', 'fukubiku'),
  ('鏡開き - 1等（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_1tou_3d.glb', 'fukubiku'),
  ('鏡開き - 2等（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_2tou_3d.glb', 'fukubiku'),
  ('鏡開き - 3等（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_3tou_3d.glb', 'fukubiku'),
  ('鏡開き - 4等（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_4tou_3d.glb', 'fukubiku'),
  ('鏡開き - 5等（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_5tou_3d.glb', 'fukubiku'),
  ('鏡開き - 6等（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_6tou_3d.glb', 'fukubiku'),
  ('鏡開き - 大当たり（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_ohatari_3d.glb', 'fukubiku'),
  ('鏡開き - 当たり（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_atari_3d.glb', 'fukubiku'),
  ('鏡開き - はずれ（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_hazure_3d.glb', 'fukubiku'),
  ('鏡開き - クーポン（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_coupon_3d.glb', 'fukubiku'),
  ('鏡開き - またね（3Dオブジェクト）', 'kagamibiraki', '/presets/kagamibiraki/kagamibiraki_cookie_3d.glb', 'fukubiku'),
  ('クリスマス - 1等（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_1tou_3d.glb', 'fukubiku'),
  ('クリスマス - 2等（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_2tou_3d.glb', 'fukubiku'),
  ('クリスマス - 3等（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_3tou_3d.glb', 'fukubiku'),
  ('クリスマス - 4等（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_4tou_3d.glb', 'fukubiku'),
  ('クリスマス - 5等（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_5tou_3d.glb', 'fukubiku'),
  ('クリスマス - 6等（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_6tou_3d.glb', 'fukubiku'),
  ('クリスマス - 大当たり（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_ohatari_3d.glb', 'fukubiku'),
  ('クリスマス - 当たり（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_atari_3d.glb', 'fukubiku'),
  ('クリスマス - はずれ（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_hazure_3d.glb', 'fukubiku'),
  ('クリスマス - クーポン（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_coupon_3d.glb', 'fukubiku'),
  ('クリスマス - またね（3Dオブジェクト）', 'xmas', '/presets/xmas/xmas_cookie_3d.glb', 'fukubiku'),
  ('自動販売機 - 1等（3Dオブジェクト）', 'vending', '/presets/vending/vending_1tou_3d.glb', 'fukubiku'),
  ('自動販売機 - 2等（3Dオブジェクト）', 'vending', '/presets/vending/vending_2tou_3d.glb', 'fukubiku'),
  ('自動販売機 - 3等（3Dオブジェクト）', 'vending', '/presets/vending/vending_3tou_3d.glb', 'fukubiku'),
  ('自動販売機 - 4等（3Dオブジェクト）', 'vending', '/presets/vending/vending_4tou_3d.glb', 'fukubiku'),
  ('自動販売機 - 5等（3Dオブジェクト）', 'vending', '/presets/vending/vending_5tou_3d.glb', 'fukubiku'),
  ('自動販売機 - 6等（3Dオブジェクト）', 'vending', '/presets/vending/vending_6tou_3d.glb', 'fukubiku'),
  ('自動販売機 - 大当たり（3Dオブジェクト）', 'vending', '/presets/vending/vending_ohatari_3d.glb', 'fukubiku'),
  ('自動販売機 - 当たり（3Dオブジェクト）', 'vending', '/presets/vending/vending_atari_3d.glb', 'fukubiku'),
  ('自動販売機 - はずれ（3Dオブジェクト）', 'vending', '/presets/vending/vending_hazure_3d.glb', 'fukubiku'),
  ('自動販売機 - クーポン（3Dオブジェクト）', 'vending', '/presets/vending/vending_coupon_3d.glb', 'fukubiku'),
  ('自動販売機 - またね（3Dオブジェクト）', 'vending', '/presets/vending/vending_cookie_3d.glb', 'fukubiku'),
  ('レシート - 1等（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_1tou_3d.glb', 'fukubiku'),
  ('レシート - 2等（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_2tou_3d.glb', 'fukubiku'),
  ('レシート - 3等（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_3tou_3d.glb', 'fukubiku'),
  ('レシート - 4等（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_4tou_3d.glb', 'fukubiku'),
  ('レシート - 5等（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_5tou_3d.glb', 'fukubiku'),
  ('レシート - 6等（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_6tou_3d.glb', 'fukubiku'),
  ('レシート - 大当たり（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_ohatari_3d.glb', 'fukubiku'),
  ('レシート - 当たり（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_atari_3d.glb', 'fukubiku'),
  ('レシート - はずれ（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_hazure_3d.glb', 'fukubiku'),
  ('レシート - クーポン（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_coupon_3d.glb', 'fukubiku'),
  ('レシート - またね（3Dオブジェクト）', 'receipt', '/presets/receipt/receipt_cookie_3d.glb', 'fukubiku'),
  ('輪投げ - 1等（3Dオブジェクト）', 'ring', '/presets/ring/ring_1tou_3d.glb', 'fukubiku'),
  ('輪投げ - 2等（3Dオブジェクト）', 'ring', '/presets/ring/ring_2tou_3d.glb', 'fukubiku'),
  ('輪投げ - 3等（3Dオブジェクト）', 'ring', '/presets/ring/ring_3tou_3d.glb', 'fukubiku'),
  ('輪投げ - 4等（3Dオブジェクト）', 'ring', '/presets/ring/ring_4tou_3d.glb', 'fukubiku'),
  ('輪投げ - 5等（3Dオブジェクト）', 'ring', '/presets/ring/ring_5tou_3d.glb', 'fukubiku'),
  ('輪投げ - 6等（3Dオブジェクト）', 'ring', '/presets/ring/ring_6tou_3d.glb', 'fukubiku'),
  ('輪投げ - 大当たり（3Dオブジェクト）', 'ring', '/presets/ring/ring_ohatari_3d.glb', 'fukubiku'),
  ('輪投げ - 当たり（3Dオブジェクト）', 'ring', '/presets/ring/ring_atari_3d.glb', 'fukubiku'),
  ('輪投げ - はずれ（3Dオブジェクト）', 'ring', '/presets/ring/ring_hazure_3d.glb', 'fukubiku'),
  ('輪投げ - クーポン（3Dオブジェクト）', 'ring', '/presets/ring/ring_coupon_3d.glb', 'fukubiku'),
  ('輪投げ - またね（3Dオブジェクト）', 'ring', '/presets/ring/ring_cookie_3d.glb', 'fukubiku'),
  ('金庫 - 1等（3Dオブジェクト）', 'safe', '/presets/safe/safe_1tou_3d.glb', 'fukubiku'),
  ('金庫 - 2等（3Dオブジェクト）', 'safe', '/presets/safe/safe_2tou_3d.glb', 'fukubiku'),
  ('金庫 - 3等（3Dオブジェクト）', 'safe', '/presets/safe/safe_3tou_3d.glb', 'fukubiku'),
  ('金庫 - 4等（3Dオブジェクト）', 'safe', '/presets/safe/safe_4tou_3d.glb', 'fukubiku'),
  ('金庫 - 5等（3Dオブジェクト）', 'safe', '/presets/safe/safe_5tou_3d.glb', 'fukubiku'),
  ('金庫 - 6等（3Dオブジェクト）', 'safe', '/presets/safe/safe_6tou_3d.glb', 'fukubiku'),
  ('金庫 - 大当たり（3Dオブジェクト）', 'safe', '/presets/safe/safe_ohatari_3d.glb', 'fukubiku'),
  ('金庫 - 当たり（3Dオブジェクト）', 'safe', '/presets/safe/safe_atari_3d.glb', 'fukubiku'),
  ('金庫 - はずれ（3Dオブジェクト）', 'safe', '/presets/safe/safe_hazure_3d.glb', 'fukubiku'),
  ('金庫 - クーポン（3Dオブジェクト）', 'safe', '/presets/safe/safe_coupon_3d.glb', 'fukubiku'),
  ('金庫 - またね（3Dオブジェクト）', 'safe', '/presets/safe/safe_cookie_3d.glb', 'fukubiku');
