-- 追加10カテゴリ(スロット/ガチャガチャ/打ち出の小槌/招き猫/だるま/ランタン/
-- 打ち上げ花火/エアー抽選機/扇子/パチンコ)の3Dテンプレートを登録する。
-- seed_object_presets.sql / seed_object_presets_v2.sql と同じ規約
-- (service='fukubiku'を明示、model_urlの一意制約でupsert)。
-- 事前に seed_object_presets.sql (unique index作成含む)を実行済みであることを前提とする。

insert into preset_objects (name, category, model_url, thumbnail_url, service) values
  ('スロット - 1等（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_1tou_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_1tou_3d_thumb.png', 'fukubiku'),
  ('スロット - 2等（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_2tou_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_2tou_3d_thumb.png', 'fukubiku'),
  ('スロット - 3等（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_3tou_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_3tou_3d_thumb.png', 'fukubiku'),
  ('スロット - 4等（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_4tou_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_4tou_3d_thumb.png', 'fukubiku'),
  ('スロット - 5等（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_5tou_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_5tou_3d_thumb.png', 'fukubiku'),
  ('スロット - 6等（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_6tou_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_6tou_3d_thumb.png', 'fukubiku'),
  ('スロット - 参加賞（3Dオブジェクト）', 'slot', 'https://app.fukubikiu.com/presets/slot/slot_cookie_3d.glb', 'https://app.fukubikiu.com/presets/slot/slot_cookie_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 1等（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_1tou_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_1tou_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 2等（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_2tou_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_2tou_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 3等（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_3tou_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_3tou_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 4等（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_4tou_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_4tou_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 5等（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_5tou_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_5tou_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 6等（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_6tou_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_6tou_3d_thumb.png', 'fukubiku'),
  ('ガチャガチャ - 参加賞（3Dオブジェクト）', 'gacha', 'https://app.fukubikiu.com/presets/gacha/gacha_cookie_3d.glb', 'https://app.fukubikiu.com/presets/gacha/gacha_cookie_3d_thumb.png', 'fukubiku'),
  ('打ち出の小槌 - 当たり（3Dオブジェクト）', 'mallet', 'https://app.fukubikiu.com/presets/mallet/mallet_atari_3d.glb', 'https://app.fukubikiu.com/presets/mallet/mallet_atari_3d_thumb.png', 'fukubiku'),
  ('打ち出の小槌 - 大当たり（3Dオブジェクト）', 'mallet', 'https://app.fukubikiu.com/presets/mallet/mallet_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/mallet/mallet_ohatari_3d_thumb.png', 'fukubiku'),
  ('打ち出の小槌 - クーポン（3Dオブジェクト）', 'mallet', 'https://app.fukubikiu.com/presets/mallet/mallet_coupon_3d.glb', 'https://app.fukubikiu.com/presets/mallet/mallet_coupon_3d_thumb.png', 'fukubiku'),
  ('打ち出の小槌 - はずれ（3Dオブジェクト）', 'mallet', 'https://app.fukubikiu.com/presets/mallet/mallet_hazure_3d.glb', 'https://app.fukubikiu.com/presets/mallet/mallet_hazure_3d_thumb.png', 'fukubiku'),
  ('打ち出の小槌 - 参加賞（3Dオブジェクト）', 'mallet', 'https://app.fukubikiu.com/presets/mallet/mallet_cookie_3d.glb', 'https://app.fukubikiu.com/presets/mallet/mallet_cookie_3d_thumb.png', 'fukubiku'),
  ('招き猫 - 当たり（3Dオブジェクト）', 'cat', 'https://app.fukubikiu.com/presets/cat/cat_atari_3d.glb', 'https://app.fukubikiu.com/presets/cat/cat_atari_3d_thumb.png', 'fukubiku'),
  ('招き猫 - 大当たり（3Dオブジェクト）', 'cat', 'https://app.fukubikiu.com/presets/cat/cat_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/cat/cat_ohatari_3d_thumb.png', 'fukubiku'),
  ('招き猫 - クーポン（3Dオブジェクト）', 'cat', 'https://app.fukubikiu.com/presets/cat/cat_coupon_3d.glb', 'https://app.fukubikiu.com/presets/cat/cat_coupon_3d_thumb.png', 'fukubiku'),
  ('招き猫 - はずれ（3Dオブジェクト）', 'cat', 'https://app.fukubikiu.com/presets/cat/cat_hazure_3d.glb', 'https://app.fukubikiu.com/presets/cat/cat_hazure_3d_thumb.png', 'fukubiku'),
  ('招き猫 - 参加賞（3Dオブジェクト）', 'cat', 'https://app.fukubikiu.com/presets/cat/cat_cookie_3d.glb', 'https://app.fukubikiu.com/presets/cat/cat_cookie_3d_thumb.png', 'fukubiku'),
  ('だるま - 1等（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_1tou_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_1tou_3d_thumb.png', 'fukubiku'),
  ('だるま - 2等（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_2tou_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_2tou_3d_thumb.png', 'fukubiku'),
  ('だるま - 3等（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_3tou_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_3tou_3d_thumb.png', 'fukubiku'),
  ('だるま - 4等（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_4tou_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_4tou_3d_thumb.png', 'fukubiku'),
  ('だるま - 5等（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_5tou_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_5tou_3d_thumb.png', 'fukubiku'),
  ('だるま - 6等（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_6tou_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_6tou_3d_thumb.png', 'fukubiku'),
  ('だるま - 参加賞（3Dオブジェクト）', 'daruma', 'https://app.fukubikiu.com/presets/daruma/daruma_cookie_3d.glb', 'https://app.fukubikiu.com/presets/daruma/daruma_cookie_3d_thumb.png', 'fukubiku'),
  ('ランタン - 当たり（3Dオブジェクト）', 'lantern', 'https://app.fukubikiu.com/presets/lantern/lantern_atari_3d.glb', 'https://app.fukubikiu.com/presets/lantern/lantern_atari_3d_thumb.png', 'fukubiku'),
  ('ランタン - 大当たり（3Dオブジェクト）', 'lantern', 'https://app.fukubikiu.com/presets/lantern/lantern_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/lantern/lantern_ohatari_3d_thumb.png', 'fukubiku'),
  ('ランタン - クーポン（3Dオブジェクト）', 'lantern', 'https://app.fukubikiu.com/presets/lantern/lantern_coupon_3d.glb', 'https://app.fukubikiu.com/presets/lantern/lantern_coupon_3d_thumb.png', 'fukubiku'),
  ('ランタン - はずれ（3Dオブジェクト）', 'lantern', 'https://app.fukubikiu.com/presets/lantern/lantern_hazure_3d.glb', 'https://app.fukubikiu.com/presets/lantern/lantern_hazure_3d_thumb.png', 'fukubiku'),
  ('ランタン - 参加賞（3Dオブジェクト）', 'lantern', 'https://app.fukubikiu.com/presets/lantern/lantern_cookie_3d.glb', 'https://app.fukubikiu.com/presets/lantern/lantern_cookie_3d_thumb.png', 'fukubiku'),
  ('打ち上げ花火 - 当たり（3Dオブジェクト）', 'firework', 'https://app.fukubikiu.com/presets/firework/firework_atari_3d.glb', 'https://app.fukubikiu.com/presets/firework/firework_atari_3d_thumb.png', 'fukubiku'),
  ('打ち上げ花火 - 大当たり（3Dオブジェクト）', 'firework', 'https://app.fukubikiu.com/presets/firework/firework_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/firework/firework_ohatari_3d_thumb.png', 'fukubiku'),
  ('打ち上げ花火 - クーポン（3Dオブジェクト）', 'firework', 'https://app.fukubikiu.com/presets/firework/firework_coupon_3d.glb', 'https://app.fukubikiu.com/presets/firework/firework_coupon_3d_thumb.png', 'fukubiku'),
  ('打ち上げ花火 - はずれ（3Dオブジェクト）', 'firework', 'https://app.fukubikiu.com/presets/firework/firework_hazure_3d.glb', 'https://app.fukubikiu.com/presets/firework/firework_hazure_3d_thumb.png', 'fukubiku'),
  ('打ち上げ花火 - 参加賞（3Dオブジェクト）', 'firework', 'https://app.fukubikiu.com/presets/firework/firework_cookie_3d.glb', 'https://app.fukubikiu.com/presets/firework/firework_cookie_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 1等（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_1tou_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_1tou_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 2等（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_2tou_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_2tou_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 3等（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_3tou_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_3tou_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 4等（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_4tou_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_4tou_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 5等（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_5tou_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_5tou_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 6等（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_6tou_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_6tou_3d_thumb.png', 'fukubiku'),
  ('エアー抽選機 - 参加賞（3Dオブジェクト）', 'airlottery', 'https://app.fukubikiu.com/presets/airlottery/airlottery_cookie_3d.glb', 'https://app.fukubikiu.com/presets/airlottery/airlottery_cookie_3d_thumb.png', 'fukubiku'),
  ('扇子 - 当たり（3Dオブジェクト）', 'fan', 'https://app.fukubikiu.com/presets/fan/fan_atari_3d.glb', 'https://app.fukubikiu.com/presets/fan/fan_atari_3d_thumb.png', 'fukubiku'),
  ('扇子 - 大当たり（3Dオブジェクト）', 'fan', 'https://app.fukubikiu.com/presets/fan/fan_ohatari_3d.glb', 'https://app.fukubikiu.com/presets/fan/fan_ohatari_3d_thumb.png', 'fukubiku'),
  ('扇子 - クーポン（3Dオブジェクト）', 'fan', 'https://app.fukubikiu.com/presets/fan/fan_coupon_3d.glb', 'https://app.fukubikiu.com/presets/fan/fan_coupon_3d_thumb.png', 'fukubiku'),
  ('扇子 - はずれ（3Dオブジェクト）', 'fan', 'https://app.fukubikiu.com/presets/fan/fan_hazure_3d.glb', 'https://app.fukubikiu.com/presets/fan/fan_hazure_3d_thumb.png', 'fukubiku'),
  ('扇子 - 参加賞（3Dオブジェクト）', 'fan', 'https://app.fukubikiu.com/presets/fan/fan_cookie_3d.glb', 'https://app.fukubikiu.com/presets/fan/fan_cookie_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 1等（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_1tou_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_1tou_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 2等（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_2tou_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_2tou_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 3等（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_3tou_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_3tou_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 4等（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_4tou_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_4tou_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 5等（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_5tou_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_5tou_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 6等（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_6tou_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_6tou_3d_thumb.png', 'fukubiku'),
  ('パチンコ - 参加賞（3Dオブジェクト）', 'pachinko', 'https://app.fukubikiu.com/presets/pachinko/pachinko_cookie_3d.glb', 'https://app.fukubikiu.com/presets/pachinko/pachinko_cookie_3d_thumb.png', 'fukubiku')
on conflict (model_url) do update set
  name = excluded.name,
  category = excluded.category,
  thumbnail_url = excluded.thumbnail_url,
  service = excluded.service;
