-- 2026-09 追加テンプレート 第3弾(8種)を preset_objects に登録する。
--
-- 射的 / 金魚すくい / かき氷 / ハロウィン / バレンタイン / 七夕 / 回転寿司 / たい焼き
-- 1テンプレートにつき6段階(1等〜6等)と4段階(大当たり/当たり/はずれ/クーポン)の両方を用意。
-- 焦らし用(<カテゴリ>_suspense_3d.glb)はファイル名から自動解決するため登録不要。
--
-- 同じ名前で二重登録されないよう、既存を消してから入れ直す。

delete from preset_objects where service = 'fukubiku' and category in ('shateki','kingyo','kakigori','halloween','valentine','tanabata','sushi','taiyaki');

insert into preset_objects (name, category, model_url, service) values
  ('射的 - 1等（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_1tou_3d.glb', 'fukubiku'),
  ('射的 - 2等（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_2tou_3d.glb', 'fukubiku'),
  ('射的 - 3等（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_3tou_3d.glb', 'fukubiku'),
  ('射的 - 4等（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_4tou_3d.glb', 'fukubiku'),
  ('射的 - 5等（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_5tou_3d.glb', 'fukubiku'),
  ('射的 - 6等（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_6tou_3d.glb', 'fukubiku'),
  ('射的 - 大当たり（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_ohatari_3d.glb', 'fukubiku'),
  ('射的 - 当たり（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_atari_3d.glb', 'fukubiku'),
  ('射的 - はずれ（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_hazure_3d.glb', 'fukubiku'),
  ('射的 - クーポン（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_coupon_3d.glb', 'fukubiku'),
  ('射的 - またね（3Dオブジェクト）', 'shateki', '/presets/shateki/shateki_cookie_3d.glb', 'fukubiku'),
  ('金魚すくい - 1等（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_1tou_3d.glb', 'fukubiku'),
  ('金魚すくい - 2等（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_2tou_3d.glb', 'fukubiku'),
  ('金魚すくい - 3等（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_3tou_3d.glb', 'fukubiku'),
  ('金魚すくい - 4等（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_4tou_3d.glb', 'fukubiku'),
  ('金魚すくい - 5等（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_5tou_3d.glb', 'fukubiku'),
  ('金魚すくい - 6等（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_6tou_3d.glb', 'fukubiku'),
  ('金魚すくい - 大当たり（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_ohatari_3d.glb', 'fukubiku'),
  ('金魚すくい - 当たり（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_atari_3d.glb', 'fukubiku'),
  ('金魚すくい - はずれ（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_hazure_3d.glb', 'fukubiku'),
  ('金魚すくい - クーポン（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_coupon_3d.glb', 'fukubiku'),
  ('金魚すくい - またね（3Dオブジェクト）', 'kingyo', '/presets/kingyo/kingyo_cookie_3d.glb', 'fukubiku'),
  ('かき氷 - 1等（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_1tou_3d.glb', 'fukubiku'),
  ('かき氷 - 2等（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_2tou_3d.glb', 'fukubiku'),
  ('かき氷 - 3等（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_3tou_3d.glb', 'fukubiku'),
  ('かき氷 - 4等（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_4tou_3d.glb', 'fukubiku'),
  ('かき氷 - 5等（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_5tou_3d.glb', 'fukubiku'),
  ('かき氷 - 6等（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_6tou_3d.glb', 'fukubiku'),
  ('かき氷 - 大当たり（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_ohatari_3d.glb', 'fukubiku'),
  ('かき氷 - 当たり（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_atari_3d.glb', 'fukubiku'),
  ('かき氷 - はずれ（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_hazure_3d.glb', 'fukubiku'),
  ('かき氷 - クーポン（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_coupon_3d.glb', 'fukubiku'),
  ('かき氷 - またね（3Dオブジェクト）', 'kakigori', '/presets/kakigori/kakigori_cookie_3d.glb', 'fukubiku'),
  ('ハロウィン - 1等（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_1tou_3d.glb', 'fukubiku'),
  ('ハロウィン - 2等（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_2tou_3d.glb', 'fukubiku'),
  ('ハロウィン - 3等（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_3tou_3d.glb', 'fukubiku'),
  ('ハロウィン - 4等（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_4tou_3d.glb', 'fukubiku'),
  ('ハロウィン - 5等（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_5tou_3d.glb', 'fukubiku'),
  ('ハロウィン - 6等（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_6tou_3d.glb', 'fukubiku'),
  ('ハロウィン - 大当たり（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_ohatari_3d.glb', 'fukubiku'),
  ('ハロウィン - 当たり（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_atari_3d.glb', 'fukubiku'),
  ('ハロウィン - はずれ（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_hazure_3d.glb', 'fukubiku'),
  ('ハロウィン - クーポン（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_coupon_3d.glb', 'fukubiku'),
  ('ハロウィン - またね（3Dオブジェクト）', 'halloween', '/presets/halloween/halloween_cookie_3d.glb', 'fukubiku'),
  ('バレンタイン - 1等（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_1tou_3d.glb', 'fukubiku'),
  ('バレンタイン - 2等（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_2tou_3d.glb', 'fukubiku'),
  ('バレンタイン - 3等（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_3tou_3d.glb', 'fukubiku'),
  ('バレンタイン - 4等（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_4tou_3d.glb', 'fukubiku'),
  ('バレンタイン - 5等（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_5tou_3d.glb', 'fukubiku'),
  ('バレンタイン - 6等（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_6tou_3d.glb', 'fukubiku'),
  ('バレンタイン - 大当たり（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_ohatari_3d.glb', 'fukubiku'),
  ('バレンタイン - 当たり（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_atari_3d.glb', 'fukubiku'),
  ('バレンタイン - はずれ（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_hazure_3d.glb', 'fukubiku'),
  ('バレンタイン - クーポン（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_coupon_3d.glb', 'fukubiku'),
  ('バレンタイン - またね（3Dオブジェクト）', 'valentine', '/presets/valentine/valentine_cookie_3d.glb', 'fukubiku'),
  ('七夕 - 1等（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_1tou_3d.glb', 'fukubiku'),
  ('七夕 - 2等（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_2tou_3d.glb', 'fukubiku'),
  ('七夕 - 3等（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_3tou_3d.glb', 'fukubiku'),
  ('七夕 - 4等（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_4tou_3d.glb', 'fukubiku'),
  ('七夕 - 5等（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_5tou_3d.glb', 'fukubiku'),
  ('七夕 - 6等（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_6tou_3d.glb', 'fukubiku'),
  ('七夕 - 大当たり（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_ohatari_3d.glb', 'fukubiku'),
  ('七夕 - 当たり（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_atari_3d.glb', 'fukubiku'),
  ('七夕 - はずれ（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_hazure_3d.glb', 'fukubiku'),
  ('七夕 - クーポン（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_coupon_3d.glb', 'fukubiku'),
  ('七夕 - またね（3Dオブジェクト）', 'tanabata', '/presets/tanabata/tanabata_cookie_3d.glb', 'fukubiku'),
  ('回転寿司 - 1等（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_1tou_3d.glb', 'fukubiku'),
  ('回転寿司 - 2等（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_2tou_3d.glb', 'fukubiku'),
  ('回転寿司 - 3等（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_3tou_3d.glb', 'fukubiku'),
  ('回転寿司 - 4等（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_4tou_3d.glb', 'fukubiku'),
  ('回転寿司 - 5等（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_5tou_3d.glb', 'fukubiku'),
  ('回転寿司 - 6等（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_6tou_3d.glb', 'fukubiku'),
  ('回転寿司 - 大当たり（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_ohatari_3d.glb', 'fukubiku'),
  ('回転寿司 - 当たり（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_atari_3d.glb', 'fukubiku'),
  ('回転寿司 - はずれ（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_hazure_3d.glb', 'fukubiku'),
  ('回転寿司 - クーポン（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_coupon_3d.glb', 'fukubiku'),
  ('回転寿司 - またね（3Dオブジェクト）', 'sushi', '/presets/sushi/sushi_cookie_3d.glb', 'fukubiku'),
  ('たい焼き - 1等（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_1tou_3d.glb', 'fukubiku'),
  ('たい焼き - 2等（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_2tou_3d.glb', 'fukubiku'),
  ('たい焼き - 3等（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_3tou_3d.glb', 'fukubiku'),
  ('たい焼き - 4等（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_4tou_3d.glb', 'fukubiku'),
  ('たい焼き - 5等（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_5tou_3d.glb', 'fukubiku'),
  ('たい焼き - 6等（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_6tou_3d.glb', 'fukubiku'),
  ('たい焼き - 大当たり（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_ohatari_3d.glb', 'fukubiku'),
  ('たい焼き - 当たり（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_atari_3d.glb', 'fukubiku'),
  ('たい焼き - はずれ（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_hazure_3d.glb', 'fukubiku'),
  ('たい焼き - クーポン（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_coupon_3d.glb', 'fukubiku'),
  ('たい焼き - またね（3Dオブジェクト）', 'taiyaki', '/presets/taiyaki/taiyaki_cookie_3d.glb', 'fukubiku');
